Repository rpm-software-management/libdnf, pull requests merged in 2019-10, with the labels that each got.

#809 Fix leaking log handlers in Sack (RhBug:1758737)
  python/hawkey/sack-py.cpp
Labels: ready for review

#814 Use POOL_FLAG_WHATPROVIDESWITHDISABLED
  libdnf.spec
  libdnf/dnf-sack.cpp
Labels: blocked

#770 [repo] Method to get all repository metadata locations
  VERSION.cmake
  libdnf.spec
  libdnf/repo/Repo-private.hpp
  libdnf/repo/Repo.cpp
  libdnf/repo/Repo.hpp
Labels: ready for review

#832 cmake: use -Werror=implicit-function-declaration only for C
  CMakeLists.txt
Labels: ready for review

#828 Catch NoModuleException (RhBug:1761773)
  libdnf/module/ModulePackageContainer.cpp
Labels: changes requested
